/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelEmpresaSlugRouteImport } from './routes/painel/$empresaSlug'
import { Route as PainelLoginRouteImport } from './routes/painel/login'
import { Route as PlataformaIndexRouteImport } from './routes/plataforma/index'
import { Route as PlataformaLoginRouteImport } from './routes/plataforma/login'
import { Route as SSlugRouteImport } from './routes/s/$slug'
import { Route as PlataformaEmpresasIdRouteImport } from './routes/plataforma/empresas/$id'
import { Route as PlataformaEmpresasNovaRouteImport } from './routes/plataforma/empresas/nova'
import { Route as PlataformaEmpresasNovaExternaRouteImport } from './routes/plataforma/empresas/nova-externa'
import { Route as SSlugIndexRouteImport } from './routes/s/$slug/index'
import { Route as SSlugCheckoutRouteImport } from './routes/s/$slug/checkout'
import { Route as SSlugFavoritesRouteImport } from './routes/s/$slug/favorites'
import { Route as SSlugLocationRouteImport } from './routes/s/$slug/location'
import { Route as SSlugOrdersRouteImport } from './routes/s/$slug/orders'
import { Route as SSlugPromotionsRouteImport } from './routes/s/$slug/promotions'
import { Route as SSlugSearchRouteImport } from './routes/s/$slug/search'
import { Route as SSlugCategoryCatSlugRouteImport } from './routes/s/$slug/category/$catSlug'
import { Route as SSlugProductIdRouteImport } from './routes/s/$slug/product/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelEmpresaSlugRoute = PainelEmpresaSlugRouteImport.update({
  id: '/painel/$empresaSlug',
  path: '/painel/$empresaSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelLoginRoute = PainelLoginRouteImport.update({
  id: '/painel/login',
  path: '/painel/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaIndexRoute = PlataformaIndexRouteImport.update({
  id: '/plataforma/',
  path: '/plataforma/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaLoginRoute = PlataformaLoginRouteImport.update({
  id: '/plataforma/login',
  path: '/plataforma/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaEmpresasIdRoute = PlataformaEmpresasIdRouteImport.update({
  id: '/plataforma/empresas/$id',
  path: '/plataforma/empresas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaEmpresasNovaRoute = PlataformaEmpresasNovaRouteImport.update({
  id: '/plataforma/empresas/nova',
  path: '/plataforma/empresas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaEmpresasNovaExternaRoute =
  PlataformaEmpresasNovaExternaRouteImport.update({
    id: '/plataforma/empresas/nova-externa',
    path: '/plataforma/empresas/nova-externa',
    getParentRoute: () => rootRouteImport,
  } as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCheckoutRoute = SSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugFavoritesRoute = SSlugFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugLocationRoute = SSlugLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugOrdersRoute = SSlugOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugPromotionsRoute = SSlugPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugSearchRoute = SSlugSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCategoryCatSlugRoute = SSlugCategoryCatSlugRouteImport.update({
  id: '/category/$catSlug',
  path: '/category/$catSlug',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugProductIdRoute = SSlugProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => SSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel/$empresaSlug': typeof PainelEmpresaSlugRoute
  '/painel/login': typeof PainelLoginRoute
  '/plataforma/login': typeof PlataformaLoginRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/plataforma/': typeof PlataformaIndexRoute
  '/plataforma/empresas/$id': typeof PlataformaEmpresasIdRoute
  '/plataforma/empresas/nova': typeof PlataformaEmpresasNovaRoute
  '/plataforma/empresas/nova-externa': typeof PlataformaEmpresasNovaExternaRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/favorites': typeof SSlugFavoritesRoute
  '/s/$slug/location': typeof SSlugLocationRoute
  '/s/$slug/orders': typeof SSlugOrdersRoute
  '/s/$slug/promotions': typeof SSlugPromotionsRoute
  '/s/$slug/search': typeof SSlugSearchRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/s/$slug/category/$catSlug': typeof SSlugCategoryCatSlugRoute
  '/s/$slug/product/$id': typeof SSlugProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel/$empresaSlug': typeof PainelEmpresaSlugRoute
  '/painel/login': typeof PainelLoginRoute
  '/plataforma/login': typeof PlataformaLoginRoute
  '/plataforma': typeof PlataformaIndexRoute
  '/plataforma/empresas/$id': typeof PlataformaEmpresasIdRoute
  '/plataforma/empresas/nova': typeof PlataformaEmpresasNovaRoute
  '/plataforma/empresas/nova-externa': typeof PlataformaEmpresasNovaExternaRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/favorites': typeof SSlugFavoritesRoute
  '/s/$slug/location': typeof SSlugLocationRoute
  '/s/$slug/orders': typeof SSlugOrdersRoute
  '/s/$slug/promotions': typeof SSlugPromotionsRoute
  '/s/$slug/search': typeof SSlugSearchRoute
  '/s/$slug': typeof SSlugIndexRoute
  '/s/$slug/category/$catSlug': typeof SSlugCategoryCatSlugRoute
  '/s/$slug/product/$id': typeof SSlugProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel/$empresaSlug': typeof PainelEmpresaSlugRoute
  '/painel/login': typeof PainelLoginRoute
  '/plataforma/login': typeof PlataformaLoginRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/plataforma/': typeof PlataformaIndexRoute
  '/plataforma/empresas/$id': typeof PlataformaEmpresasIdRoute
  '/plataforma/empresas/nova': typeof PlataformaEmpresasNovaRoute
  '/plataforma/empresas/nova-externa': typeof PlataformaEmpresasNovaExternaRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/favorites': typeof SSlugFavoritesRoute
  '/s/$slug/location': typeof SSlugLocationRoute
  '/s/$slug/orders': typeof SSlugOrdersRoute
  '/s/$slug/promotions': typeof SSlugPromotionsRoute
  '/s/$slug/search': typeof SSlugSearchRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/s/$slug/category/$catSlug': typeof SSlugCategoryCatSlugRoute
  '/s/$slug/product/$id': typeof SSlugProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/painel/$empresaSlug'
    | '/painel/login'
    | '/plataforma/login'
    | '/s/$slug'
    | '/plataforma/'
    | '/plataforma/empresas/$id'
    | '/plataforma/empresas/nova'
    | '/plataforma/empresas/nova-externa'
    | '/s/$slug/checkout'
    | '/s/$slug/favorites'
    | '/s/$slug/location'
    | '/s/$slug/orders'
    | '/s/$slug/promotions'
    | '/s/$slug/search'
    | '/s/$slug/'
    | '/s/$slug/category/$catSlug'
    | '/s/$slug/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/painel/$empresaSlug'
    | '/painel/login'
    | '/plataforma/login'
    | '/plataforma'
    | '/plataforma/empresas/$id'
    | '/plataforma/empresas/nova'
    | '/plataforma/empresas/nova-externa'
    | '/s/$slug/checkout'
    | '/s/$slug/favorites'
    | '/s/$slug/location'
    | '/s/$slug/orders'
    | '/s/$slug/promotions'
    | '/s/$slug/search'
    | '/s/$slug'
    | '/s/$slug/category/$catSlug'
    | '/s/$slug/product/$id'
  id:
    | '__root__'
    | '/'
    | '/painel/$empresaSlug'
    | '/painel/login'
    | '/plataforma/login'
    | '/s/$slug'
    | '/plataforma/'
    | '/plataforma/empresas/$id'
    | '/plataforma/empresas/nova'
    | '/plataforma/empresas/nova-externa'
    | '/s/$slug/checkout'
    | '/s/$slug/favorites'
    | '/s/$slug/location'
    | '/s/$slug/orders'
    | '/s/$slug/promotions'
    | '/s/$slug/search'
    | '/s/$slug/'
    | '/s/$slug/category/$catSlug'
    | '/s/$slug/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelEmpresaSlugRoute: typeof PainelEmpresaSlugRoute
  PainelLoginRoute: typeof PainelLoginRoute
  PlataformaLoginRoute: typeof PlataformaLoginRoute
  SSlugRoute: typeof SSlugRouteWithChildren
  PlataformaIndexRoute: typeof PlataformaIndexRoute
  PlataformaEmpresasIdRoute: typeof PlataformaEmpresasIdRoute
  PlataformaEmpresasNovaRoute: typeof PlataformaEmpresasNovaRoute
  PlataformaEmpresasNovaExternaRoute: typeof PlataformaEmpresasNovaExternaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/$empresaSlug': {
      id: '/painel/$empresaSlug'
      path: '/painel/$empresaSlug'
      fullPath: '/painel/$empresaSlug'
      preLoaderRoute: typeof PainelEmpresaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/login': {
      id: '/painel/login'
      path: '/painel/login'
      fullPath: '/painel/login'
      preLoaderRoute: typeof PainelLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma/': {
      id: '/plataforma/'
      path: '/plataforma'
      fullPath: '/plataforma/'
      preLoaderRoute: typeof PlataformaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma/login': {
      id: '/plataforma/login'
      path: '/plataforma/login'
      fullPath: '/plataforma/login'
      preLoaderRoute: typeof PlataformaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma/empresas/$id': {
      id: '/plataforma/empresas/$id'
      path: '/plataforma/empresas/$id'
      fullPath: '/plataforma/empresas/$id'
      preLoaderRoute: typeof PlataformaEmpresasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma/empresas/nova': {
      id: '/plataforma/empresas/nova'
      path: '/plataforma/empresas/nova'
      fullPath: '/plataforma/empresas/nova'
      preLoaderRoute: typeof PlataformaEmpresasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma/empresas/nova-externa': {
      id: '/plataforma/empresas/nova-externa'
      path: '/plataforma/empresas/nova-externa'
      fullPath: '/plataforma/empresas/nova-externa'
      preLoaderRoute: typeof PlataformaEmpresasNovaExternaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/': {
      id: '/s/$slug/'
      path: '/'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/checkout': {
      id: '/s/$slug/checkout'
      path: '/checkout'
      fullPath: '/s/$slug/checkout'
      preLoaderRoute: typeof SSlugCheckoutRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/favorites': {
      id: '/s/$slug/favorites'
      path: '/favorites'
      fullPath: '/s/$slug/favorites'
      preLoaderRoute: typeof SSlugFavoritesRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/location': {
      id: '/s/$slug/location'
      path: '/location'
      fullPath: '/s/$slug/location'
      preLoaderRoute: typeof SSlugLocationRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/orders': {
      id: '/s/$slug/orders'
      path: '/orders'
      fullPath: '/s/$slug/orders'
      preLoaderRoute: typeof SSlugOrdersRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/promotions': {
      id: '/s/$slug/promotions'
      path: '/promotions'
      fullPath: '/s/$slug/promotions'
      preLoaderRoute: typeof SSlugPromotionsRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/search': {
      id: '/s/$slug/search'
      path: '/search'
      fullPath: '/s/$slug/search'
      preLoaderRoute: typeof SSlugSearchRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/category/$catSlug': {
      id: '/s/$slug/category/$catSlug'
      path: '/category/$catSlug'
      fullPath: '/s/$slug/category/$catSlug'
      preLoaderRoute: typeof SSlugCategoryCatSlugRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/product/$id': {
      id: '/s/$slug/product/$id'
      path: '/product/$id'
      fullPath: '/s/$slug/product/$id'
      preLoaderRoute: typeof SSlugProductIdRouteImport
      parentRoute: typeof SSlugRoute
    }
  }
}

interface SSlugRouteChildren {
  SSlugCheckoutRoute: typeof SSlugCheckoutRoute
  SSlugFavoritesRoute: typeof SSlugFavoritesRoute
  SSlugLocationRoute: typeof SSlugLocationRoute
  SSlugOrdersRoute: typeof SSlugOrdersRoute
  SSlugPromotionsRoute: typeof SSlugPromotionsRoute
  SSlugSearchRoute: typeof SSlugSearchRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
  SSlugCategoryCatSlugRoute: typeof SSlugCategoryCatSlugRoute
  SSlugProductIdRoute: typeof SSlugProductIdRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugCheckoutRoute: SSlugCheckoutRoute,
  SSlugFavoritesRoute: SSlugFavoritesRoute,
  SSlugLocationRoute: SSlugLocationRoute,
  SSlugOrdersRoute: SSlugOrdersRoute,
  SSlugPromotionsRoute: SSlugPromotionsRoute,
  SSlugSearchRoute: SSlugSearchRoute,
  SSlugIndexRoute: SSlugIndexRoute,
  SSlugCategoryCatSlugRoute: SSlugCategoryCatSlugRoute,
  SSlugProductIdRoute: SSlugProductIdRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelEmpresaSlugRoute: PainelEmpresaSlugRoute,
  PainelLoginRoute: PainelLoginRoute,
  PlataformaLoginRoute: PlataformaLoginRoute,
  SSlugRoute: SSlugRouteWithChildren,
  PlataformaIndexRoute: PlataformaIndexRoute,
  PlataformaEmpresasIdRoute: PlataformaEmpresasIdRoute,
  PlataformaEmpresasNovaRoute: PlataformaEmpresasNovaRoute,
  PlataformaEmpresasNovaExternaRoute: PlataformaEmpresasNovaExternaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
